projet NetBeans/applis-jee-mbds-ITUB/src/java/applisjee/mbds/itub/ejb/entity/Utilisateur.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applisjee.mbds.itub.ejb.entity;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Mirado
 */
@Entity
@Table(name = "UTILISATEUR")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Utilisateur.findAll", query = "SELECT u FROM Utilisateur u"),
    @NamedQuery(name = "Utilisateur.findByPseudo", query = "SELECT u FROM Utilisateur u WHERE u.pseudo = :pseudo"),
    @NamedQuery(name = "Utilisateur.findByEmail", query = "SELECT u FROM Utilisateur u WHERE u.email = :email"),
    @NamedQuery(name = "Utilisateur.findByNom", query = "SELECT u FROM Utilisateur u WHERE u.nom = :nom"),
    @NamedQuery(name = "Utilisateur.findByPrenom", query = "SELECT u FROM Utilisateur u WHERE u.prenom = :prenom"),
    @NamedQuery(name = "Utilisateur.findByDateDeNaissance", query = "SELECT u FROM Utilisateur u WHERE u.dateDeNaissance = :dateDeNaissance"),
    @NamedQuery(name = "Utilisateur.findByMotDePasse", query = "SELECT u FROM Utilisateur u WHERE u.motDePasse = :motDePasse")})
public class Utilisateur implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @Column(name = "PSEUDO")
    private String pseudo;
    @Column(name = "EMAIL")
    private String email;
    @Column(name = "NOM")
    private String nom;
    @Column(name = "PRENOM")
    private String prenom;
    @Column(name = "DATE_DE_NAISSANCE")
    @Temporal(TemporalType.DATE)
    private Date dateDeNaissance;
    @Lob
    @Basic(fetch = FetchType.LAZY)
    @Column(name = "PHOTO")
    private Serializable photo;
    @Column(name = "MOT_DE_PASSE")
    private String motDePasse;
    @OneToOne(cascade = CascadeType.ALL, mappedBy = "utilisateur")
    private UtilisateurRole utilisateurRole;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "utilisateur")
    private Collection<Question> questionCollection;
    
//    @OneToMany(cascade = CascadeType.ALL, mappedBy = "utilisateur")
//    private Collection<Question> questionCollection;
    
    /**
     * constructeur
     */
    public Utilisateur() {
    }

    /**
     *
     * @param pseudo
     */
    public Utilisateur(String pseudo) {
        this.pseudo = pseudo;
    }

    /**
     *
     * @return
     */
    public String getPseudo() {
        return pseudo;
    }

    /**
     *
     * @param pseudo
     */
    public void setPseudo(String pseudo) {
        this.pseudo = pseudo;
    }

    /**
     *
     * @return
     */
    public String getEmail() {
        return email;
    }

    /**
     *
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     *
     * @return
     */
    public String getNom() {
        return nom;
    }

    /**
     *
     * @param nom
     */
    public void setNom(String nom) {
        this.nom = nom;
    }

    /**
     *
     * @return
     */
    public String getPrenom() {
        return prenom;
    }

    /**
     *
     * @param prenom
     */
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    /**
     *
     * @return
     */
    public Date getDateDeNaissance() {
        return dateDeNaissance;
    }

    /**
     *
     * @param dateDeNaissance
     */
    public void setDateDeNaissance(Date dateDeNaissance) {
        this.dateDeNaissance = dateDeNaissance;
    }

    /**
     *
     * @return
     */
    public Serializable getPhoto() {
        return photo;
    }
    
    /**
     *
     * @param photo
     */
    public void setPhoto(Serializable photo) {
        this.photo = photo;
    }

    /**
     *
     * @return
     */
    public String getMotDePasse() {
        return motDePasse;
    }

    /**
     *
     * @param motDePasse
     */
    public void setMotDePasse(String motDePasse) {
        this.motDePasse = motDePasse;
    }

    /**
     *
     * @return
     */
    public UtilisateurRole getUtilisateurRole() {
        return utilisateurRole;
    }

    /**
     *
     * @param utilisateurRole
     */
    public void setUtilisateurRole(UtilisateurRole utilisateurRole) {
        this.utilisateurRole = utilisateurRole;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (pseudo != null ? pseudo.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Utilisateur)) {
            return false;
        }
        Utilisateur other = (Utilisateur) object;
        if ((this.pseudo == null && other.pseudo != null) || (this.pseudo != null && !this.pseudo.equals(other.pseudo))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "applisjee.mbds.itub.ejb.entity.Utilisateur[ pseudo=" + pseudo + " ]";
    }

}

projet NetBeans/applis-jee-mbds-ITUB/src/java/applisjee/mbds/itub/jsf/backingbean/UtilisateurMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applisjee.mbds.itub.jsf.backingbean;

import applisjee.mbds.itub.ejb.entity.Utilisateur;
import applisjee.mbds.itub.ejb.session.UtilisateurManager;
import applisjee.mbds.itub.jsf.util.Util;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;

/**
 *
 * @author Mirado
 */
@Named(value = "utilisateurMBean")
@RequestScoped
public class UtilisateurMBean {
    
    private List<Utilisateur> utilisateurList;
    
    @EJB
    private UtilisateurManager utilisateurManager;

    /**
     *
     * @return
     */
    public List<Utilisateur> getAllUtilisateur() {
        return utilisateurManager.findAll();
    }
    
    /**
     *
     * @param u
     * @return
     */
    public String supprimerCompte(Utilisateur u){
        utilisateurManager.supprimerCompte(u);
        Util.addFlashInfoMessage("Compte de " + u.getPseudo()+ " supprimé");
        return "/admin/utilisateur/index?faces-redirect=true";
    }
}

projet NetBeans/applis-jee-mbds-ITUB/web/admin/utilisateur/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <f:metadata>
        <f:viewAction action="#{internationalisation.loadLang()}"/>
    </f:metadata>  

    <body>
        <ui:composition template="/WEB-INF/templates/primeface_top_left_foot.xhtml">
            <ui:define name="top">
                <p:menuitem value="Admin" outcome="/admin/utilisateur/index" />
                <p:menuitem value="Utilisateur" outcome="/admin/utilisateur/index" />
            </ui:define>

            <ui:define name="content">
                <f:view>
                    <h:form>
                        <h1><h:outputText value="Liste des utilisateurs"/></h1>
                        <p:dataTable value="#{utilisateurMBean.allUtilisateur}" var="item">
                            <p:column style="text-align:center;">
                                <f:facet name="header">
                                    <h:outputText value="Pseudo"/>
                                </f:facet>
                                <h:outputText value="#{item.pseudo}"/>
                            </p:column>
                            <p:column style="text-align:center;" width="300">
                                <f:facet name="header">
                                    <h:outputText value="Email"/>
                                </f:facet>
                                <h:outputText value="#{item.email}"/>
                            </p:column>
                            <p:column style="text-align:center;">
                                <f:facet name="header">
                                    <h:outputText value="Nom"/>
                                </f:facet>
                                <h:outputText value="#{item.nom}"/>
                            </p:column>
                            <p:column style="text-align:center;">
                                <f:facet name="header">
                                    <h:outputText value="Prenom"/>
                                </f:facet>
                                <h:outputText value="#{item.prenom}"/>
                            </p:column>
                            <p:column style="text-align:center;">
                                <f:facet name="header">
                                    <h:outputText value="Date de naissance"/>
                                </f:facet>
                                <h:outputText value="#{item.dateDeNaissance}">
                                    <f:convertDateTime pattern="dd/MM/yyyy" />
                                </h:outputText>
                            </p:column>

                            <p:column style="text-align:center;">
                                <f:facet name="header">
                                    <h:outputText value="Opérations"/>
                                </f:facet>
                                <p:link value="Modifier" outcome="/admin/utilisateur/modification">
                                    <f:param name="pseudo" value="#{item.pseudo}"/>
                                </p:link> &nbsp;&nbsp;&nbsp;
                                <h:commandLink 
                                    action="#{utilisateurMBean.supprimerCompte(item)}"
                                    title="Supprimer le compte de #{item.nom}" >
                                    <h:graphicImage name="images/del.png"/>
                                </h:commandLink> 
                            </p:column>
                        </p:dataTable>
                    </h:form>
                </f:view>
            </ui:define>
        </ui:composition>
    </body>
</html>

projet NetBeans/applis-jee-mbds-ITUB/web/admin/utilisateur/modification.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    
    <f:metadata>
        <f:viewAction action="#{internationalisation.loadLang()}"/>
    </f:metadata>  

    <body>
        <ui:composition template="/WEB-INF/templates/primeface_top_left_foot.xhtml">
            <ui:define name="metadata">
                <f:metadata>
                    <f:viewParam name="pseudo" value="#{modificationUtilisateurMBean.pseudo}"/>
                    <f:viewAction action="#{modificationUtilisateurMBean.chargerUtilisateur()}"/>
                </f:metadata> 
            </ui:define>

            <ui:define name="top">
                <p:menuitem value="Admin" outcome="/admin/index" />
                <p:menuitem value="Utilisateur" outcome="/admin/utilisateur/index" />
                <p:menuitem value="Modification" outcome="/admin/utilisateur/modification" />
            </ui:define>

            <ui:define name="content">
                <f:view>
                    <h:form>
                        <h1><h:outputText value="Modification #{modificationUtilisateurMBean.utilisateur.pseudo}"/></h1>
                        <p:panelGrid columns="2">
                            <p:outputLabel value="Pseudo:" for="pseudo" />
                            <p:inputText id="pseudo" value="#{modificationUtilisateurMBean.utilisateur.pseudo}" title="Pseudo" required="true" requiredMessage="The Pseudo field is required."/>
                            <p:outputLabel value="Email:" for="email" />
                            <p:inputText id="email" value="#{modificationUtilisateurMBean.utilisateur.email}" title="Email" />
                            <p:outputLabel value="Nom:" for="nom" />
                            <p:inputText id="nom" value="#{modificationUtilisateurMBean.utilisateur.nom}" title="Nom" />
                            <p:outputLabel value="Prenom:" for="prenom" />
                            <p:inputText id="prenom" value="#{modificationUtilisateurMBean.utilisateur.prenom}" title="Prenom" />
                            <p:outputLabel value="Date de naissance" for="dateDeNaissance" />

                            <p:calendar 
                                id="dateDeNaissance" 
                                value="#{modificationUtilisateurMBean.utilisateur.dateDeNaissance}" 
                                title="Date de naissance" >
                                <f:convertDateTime pattern="dd/MM/yy" />
                            </p:calendar>
                        </p:panelGrid>
                        <br/>
                        <p:commandButton id='enregistrer'
                                         action='#{modificationUtilisateurMBean.enregistrer()}'
                                         value='Enregistrer'
                                         rendered='#{modificationUtilisateurMBean.utilisateur != null}'>
                        </p:commandButton>
                    </h:form>
                </f:view>
            </ui:define>
        </ui:composition>
    </body>
</html>