projet NetBeans/applis-jee-mbds-ITUB/src/java/applisjee/mbds/itub/ejb/entity/Reponse.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applisjee.mbds.itub.ejb.entity;

import applisjee.mbds.itub.util.Util;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Mirado
 */
@Entity
@Table(name = "REPONSE")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Reponse.findAll", query = "SELECT r FROM Reponse r"),
    @NamedQuery(name = "Reponse.findByIdQuestion", query = "SELECT r FROM Reponse r WHERE r.question.questionId = :questionId"), //    @NamedQuery(name = "Customer.findByAddressline1", query = "SELECT c FROM Customer c WHERE c.addressline1 = :addressline1"),
//    @NamedQuery(name = "Customer.findByAddressline2", query = "SELECT c FROM Customer c WHERE c.addressline2 = :addressline2"),
//    @NamedQuery(name = "Customer.findByCity", query = "SELECT c FROM Customer c WHERE c.city = :city"),
//    @NamedQuery(name = "Customer.findByState", query = "SELECT c FROM Customer c WHERE c.state = :state"),
//    @NamedQuery(name = "Customer.findByPhone", query = "SELECT c FROM Customer c WHERE c.phone = :phone"),
//    @NamedQuery(name = "Customer.findByFax", query = "SELECT c FROM Customer c WHERE c.fax = :fax"),
//    @NamedQuery(name = "Customer.findByEmail", query = "SELECT c FROM Customer c WHERE c.email = :email"),
//    @NamedQuery(name = "Customer.findByCreditLimit", query = "SELECT c FROM Customer c WHERE c.creditLimit = :creditLimit")
})
public class Reponse implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Column(name = "REPONSE_ID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long ReponseId;

    @Lob
    @Column(name = "REPONSE")
    private String reponse;

    @Column(name = "DATE_REPONSE")
    @Temporal(TemporalType.DATE)
    private Date dateReponse;

    @Column(name = "VOTE")
    private Integer vote;

    @Column(name = "VUE")
    private Boolean vue;

    @JoinColumn(name = "UTILISATEUR", referencedColumnName = "PSEUDO")
    @ManyToOne(optional = false)
    private Utilisateur utilisateur;

    @JoinColumn(name = "QUESTION", referencedColumnName = "QUESTION_ID")
    @ManyToOne(optional = false)
    private Question question;

    @Version
    private int version;

    /**
     * constructeur
     */
    public Reponse() {

    }

    /**
     *
     * @param reponse
     * @param dateReponse
     * @param vote
     * @param vue
     * @param utilisateur
     * @param question
     */
    public Reponse(String reponse, Date dateReponse, Integer vote, Boolean vue, Utilisateur utilisateur, Question question) {
        this.reponse = reponse;
        this.dateReponse = dateReponse;
        this.vote = vote;
        this.vue = vue;
        this.utilisateur = utilisateur;
        this.question = question;
    }

    /**
     *
     * @return
     */
    public Long getReponseId() {
        return ReponseId;
    }

    /**
     *
     * @param ReponseId
     */
    public void setReponseId(Long ReponseId) {
        this.ReponseId = ReponseId;
    }

    /**
     *
     * @return
     */
    public String getReponse() {
        return reponse;
    }

    /**
     *
     * @param reponse
     */
    public void setReponse(String reponse) {
        this.reponse = reponse;
    }

    /**
     *
     * @return
     */
    public Date getDateReponse() {
        return dateReponse;
    }

    /**
     *
     * @param dateReponse
     */
    public void setDateReponse(Date dateReponse) {
        this.dateReponse = dateReponse;
    }

    /**
     *
     * @return
     */
    public String getDateFormat() {
        return Util.formatDate(dateReponse);
    }

    /**
     *
     * recupère le temps écoulé depuis la date de creation de la réponse
     *
     * @return
     */
    public String getTempEcoule() {
        String ret = "";
        if (this.dateReponse != null) {
            LocalDate now = LocalDate.now();
            LocalDate lDateQuestion = this.dateReponse.toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();

            Period period = Period.between(lDateQuestion, now);
            int diff = period.getDays();

            int year = period.getYears();
            if (period.getYears() > 0) {
                ret += year + " an(s)";
            }

            int month = period.getMonths();
            if (month > 0) {
                ret += " " + month + " mois";
            }

            int jour = period.getDays();
            if (jour >= 0) {
                ret += " " + jour + " jour(s)";
            }
        }

        return ret;
    }

    /**
     *
     * @return
     */
    public Integer getVote() {
        return vote;
    }

    /**
     *
     * @param vote
     */
    public void setVote(Integer vote) {
        this.vote = vote;
    }

    /**
     *
     * @return
     */
    public Utilisateur getUtilisateur() {
        return utilisateur;
    }

    /**
     *
     * @param utilisateur
     */
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    /**
     *
     * @return
     */
    public Question getQuestion() {
        return question;
    }

    /**
     *
     * @param question
     */
    public void setQuestion(Question question) {
        this.question = question;
    }

    /**
     *
     * @return
     */
    public int getVersion() {
        return version;
    }

    /**
     *
     * @param version
     */
    public void setVersion(int version) {
        this.version = version;
    }

    /**
     *
     * @return
     */
    public Boolean getVue() {
        return vue;
    }

    /**
     *
     * @return
     */
    public String getVueStr() {
        if (vue) {
            return "";
        }
        
        return "(non vue)";
    }

    /**
     *
     * @param vue
     */
    public void setVue(Boolean vue) {
        this.vue = vue;
    }
}

projet NetBeans/applis-jee-mbds-ITUB/src/java/applisjee/mbds/itub/jsf/backingbean/AccueilBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applisjee.mbds.itub.jsf.backingbean;

import applisjee.mbds.itub.ejb.entity.Question;
import applisjee.mbds.itub.ejb.session.QuestionManager;
import applisjee.mbds.itub.jsf.util.Util;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.context.ExternalContext;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;

/**
 *
 * @author Andrianina_pc
 */
@Named(value = "accueilBean")
@ViewScoped
public class AccueilBean implements Serializable {

    @EJB
    private QuestionManager questionManager;

    @Inject
    private ExternalContext externalContext;

    private List<Question> questionList;

    private String pseudoUtilisateur = " ";

    /**
     *
     * @return
     */
    public List<Question> getQuestions() {
        
        if (questionList == null) {
            questionList = questionManager.findAll();
        }
        return questionList;
    }

    /**
     *
     * @param question
     */
    public void resolu(Question question) {
        questionManager.marquerResolu(question);
        Util.addFlashInfoMessage("Marquer comme résolu");
    }

    /**
     *
     * @return
     */
    public String getPseudoUtilisateur() {
        HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();
        if (request.getUserPrincipal() != null) {
            String pseudo = request.getUserPrincipal().getName();
            pseudoUtilisateur = pseudo;
        }
        return pseudoUtilisateur;
    }

}

projet NetBeans/applis-jee-mbds-ITUB/web/accueil.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <f:metadata>
        <f:viewAction action="#{internationalisation.loadLang()}"/>
    </f:metadata> 

    <h:head>
        <title>Accueil</title>
    </h:head>

    <body>
        <ui:composition template="/WEB-INF/templates/primeface_top_left_foot.xhtml">

            <ui:param name="nbNotification" value="#{notificationMBean.nbNotification}" />
            <ui:define name="top">
                <p:menuitem value="#{msg.Accueil}" url="accueil.xhtml" />
            </ui:define>

            <ui:define name="content">
                <p:panel>
                    <p:panelGrid>
                        <h:form>
                            <h:outputLabel value="#{msg['Mot-cle']} : " style="" for="motcle"/>
                            <h:inputText id="motcle" value="#{accueilMBean.motcle}" style=""/>
                            <h:outputLabel value="#{msg['TitreOuContenue']} : " style="margin-left: 50px" for="texte"/>
                            <h:inputText id="texte" value="#{accueilMBean.texte}" style="width: 600px;margin-right: 40px"/>
                            <p:commandButton  value="#{msg['Rechercher']}" id="ajax" action="#{accueilMBean.getSearchQuestion(accueilMBean.motcle, accueilMBean.texte)}" 
                                                  style="margin-right:20px;" styleClass="ui-priority-primary"/>
                        </h:form>
                    </p:panelGrid>
                </p:panel>
                <p:dataScroller value="#{accueilMBean.questionList}" var="item">
                    <p:panel header="#{item.getDateFormat()}" toggleable="true" toggleSpeed="500" closeSpeed="500" widgetVar="panel" style="margin-bottom:20px">
                        <h:panelGrid columns="2" cellpadding="10">
                            <h:panelGrid style="text-align: center">
                                <h1>#{item.utilisateur.pseudo}</h1>
                                <p:graphicImage style="width:250px" library="images" name="profil/avatar.jpg" alt="profil" />
                                <p:dataList value="#{item.getAllMotCle()}" var="keyword" type="ordered">
                                    <f:facet name="header">
                                        Mot Clé(s)
                                    </f:facet>
                                    #{keyword}<br/><br/>
                                </p:dataList>
                            </h:panelGrid>
                            <h:panelGrid columns="1" cellpadding="10">
                                <h1>#{item.titre}</h1>
                                <!--<h:outputText value="#{item.question}" escape="false" />-->
                            </h:panelGrid>
                        </h:panelGrid>
                        <p:panel style="text-align: right; border: 0px solid black">
                            <p:link outcome="/detail_question" style="color:blue" value="#{msg['Voir-details']}">
                                <f:param name="idQuestion" value="#{item.questionId}" />
                            </p:link>
                            <h:form rendered="#{accueilBean.pseudoUtilisateur.compareToIgnoreCase(item.utilisateur.pseudo)==0 and (item.resolu==false or item.resolu==null)}" style="float: left">
                                <p:commandButton  value="Marquer comme résolue" id="ajax" action="#{accueilBean.resolu(item)}" 
                                                  style="margin-right:20px;" styleClass="ui-priority-primary"/>
                            </h:form>
                            <h:outputLabel rendered="#{item.resolu==true}" style="float: left;color: green" value="Résolue"></h:outputLabel>
                        </p:panel>
                    </p:panel>
                </p:dataScroller>
            </ui:define>
        </ui:composition>
    </body>
</html>

projet NetBeans/applis-jee-mbds-ITUB/web/detail_question.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <f:metadata>  
        <f:viewParam name="idQuestion" value="#{detailQuestionMBean.questionId}"  
                     required="true"/> 

        <f:viewAction action="#{detailQuestionMBean.loadQuestion()}"/>
        <f:viewAction action="#{internationalisation.loadLang()}"/>
    </f:metadata>
    <body>
        <ui:composition template="/WEB-INF/templates/primeface_top_left_foot.xhtml">
            <ui:param name="nbNotification" value="#{notificationMBean.nbNotification}" />
            <ui:define name="top">             
                <p:menuitem value="Question #{detailQuestionMBean.questionId}" url="detail_question.xhtml?idQuestion=#{detailQuestionMBean.questionId}" />                
            </ui:define>
            <ui:define name="content">

                <p:growl id="msgs" showDetail="true" />
                <p:fieldset legend="Question du #{detailQuestionMBean.question.getDateFormat()}" style="margin-bottom:20px" toggleable="true" toggleSpeed="500">
                    <h:panelGrid columns="2" cellpadding="10">
                        <h:panelGrid style="text-align: center">
                            <h1>#{detailQuestionMBean.question.utilisateur.pseudo}</h1>
                            <p:graphicImage style="width:250px" library="images" name="profil/avatar.jpg" alt="profil" />
                            <p:dataList value="#{detailQuestionMBean.question.getAllMotCle()}" var="keyword" type="ordered">
                                <f:facet name="header">
                                    Mot Clé(s)
                                </f:facet>
                                #{keyword}<br/><br/>
                            </p:dataList>
                        </h:panelGrid>
                        <h:panelGrid columns="1" cellpadding="10">
                            <h2>#{detailQuestionMBean.question.titre}</h2>
                            <h:outputText value="#{detailQuestionMBean.question.question}" escape="false" />

                        </h:panelGrid>
                    </h:panelGrid>


                    <p:panel style="text-align: right; border: 0px solid black">
                        il y a #{detailQuestionMBean.question.tempEcoule}
                    </p:panel>
                </p:fieldset>

                <p:fieldset legend="Liste des réponses (#{detailQuestionMBean.question.reponsesCollection.size()})" toggleable="true" toggleSpeed="500" style="border: 0px solid black">
                    <p:dataScroller value="#{detailQuestionMBean.question.reponsesCollection}" var="item">
                        <p:fieldset legend="#{item.utilisateur.pseudo} le #{item.getDateFormat()}" toggleable="true" toggleSpeed="500" style="border: 0px solid black">
                            <h:panelGrid columns="2" cellpadding="10">
                                <h:panelGrid style="text-align: center">
                                    <h1>#{item.utilisateur.pseudo}</h1>
                                    <p:graphicImage style="width:150px" library="images" name="profil/avatar.jpg" alt="profil" />

                                    <h:panelGrid columns="3" cellpadding="10">
                                        <h:panelGrid>
                                            <p:commandButton action="#{detailQuestionMBean.voteMoins(item.reponseId)}" value="-" immediate="true"/>
                                        </h:panelGrid>

                                        <h:panelGrid columns="1" cellpadding="10" style="text-align: center">
                                            <h:outputText value="#{item.vote}" escape="false" />
                                        </h:panelGrid>

                                        <h:panelGrid>
                                            <p:commandButton action="#{detailQuestionMBean.votePlus(item.reponseId)}" value="+" immediate="true"/>

                                        </h:panelGrid>
                                    </h:panelGrid>


                                </h:panelGrid>
                                <h:panelGrid columns="1" cellpadding="10">
                                    <h:outputText value="#{item.reponse}" escape="false" />
                                </h:panelGrid>
                            </h:panelGrid>

                            <p:panel style="text-align: right; border: 0px solid black">
                                il y a #{item.tempEcoule}
                            </p:panel>
                        </p:fieldset>
                    </p:dataScroller>
                </p:fieldset>
                <div class="ui-g">
                    <div class="ui-g-12" style="text-align: center">
                        <p:linkButton rendered="#{!detailQuestionMBean.question.resolu.booleanValue()}" outcome="/connect/add_reponse" value="#{msg.laisser_une_reponse}" style="text-align: center;color:blue">
                            <f:param name="idQuestion" value="#{detailQuestionMBean.questionId}" />
                        </p:linkButton>
                    </div>
                </div>
            </ui:define>
        </ui:composition>
    </body>
</html>