projet NetBeans/applis-jee-mbds-ITUB/src/java/applisjee/mbds/itub/jsf/backingbean/UtilisateurRoleMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applisjee.mbds.itub.jsf.backingbean;

import applisjee.mbds.itub.ejb.entity.UtilisateurRole;
import applisjee.mbds.itub.ejb.session.UtilisateurRoleManager;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.faces.view.ViewScoped;

/**
 *
 * @author Mirado
 */
@Named(value = "utilisateurRoleMBean")
@ViewScoped
public class UtilisateurRoleMBean implements Serializable{

    @EJB
    private UtilisateurRoleManager utilisateurRoleManager;
    
    private String pseudo;
    
    private UtilisateurRole utilisateurRole;

    /**
     *
     * @return
     */
    public List<UtilisateurRole> getAllUtilisateurRole() {
        return utilisateurRoleManager.getAllUtilisateurRole();
    }

    /**
     *
     * @return
     */
    public UtilisateurRole getUtilisateurRole() {
        return utilisateurRole;
    }

    /**
     *
     * @return
     */
    public String getPseudo() {
        return pseudo;
    }

    /**
     *
     * @param pseudo
     */
    public void setPseudo(String pseudo) {
        this.pseudo = pseudo;
    }
    
    /**
     * charger le role utilisateur
     */
    public void loadUtilisateurRole(){
        utilisateurRole = utilisateurRoleManager.findByPseudo(pseudo);
    }
    
    /**
     *modifier role utilisateur
     * @return
     */
    public String modifier(){
        utilisateurRoleManager.update(utilisateurRole);
        return "/admin/role/index?faces-redirect=true";
    }
}

projet NetBeans/applis-jee-mbds-ITUB/web/admin/role/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <f:metadata>
        <f:viewAction action="#{internationalisation.loadLang()}"/>
    </f:metadata>  

    <body>
        <ui:composition template="/WEB-INF/templates/primeface_top_left_foot.xhtml">

            <ui:define name="top">
                <p:menuitem value="Admin" outcome="/admin/utilisateur/index" />
                <p:menuitem value="Utilisateur Role" outcome="/admin/role/index" />
            </ui:define>

            <ui:define name="content">
                <f:view>
                    <h:form>
                        <h1><h:outputText value="Liste des roles utilisateurs"/></h1>

                        <br/><br/>
                        <p:dataTable value="#{utilisateurRoleMBean.allUtilisateurRole}" var="item">
                            <p:column style="text-align: center">
                                <f:facet name="header">
                                    <h:outputText value="Pseudo"/>
                                </f:facet>
                                <h:outputText value="#{item.pseudo}"/>
                            </p:column>
                            <p:column style="text-align: center">
                                <f:facet name="header">
                                    <h:outputText value="Role"/>
                                </f:facet>
                                <h:outputText value="#{item.role}"/>
                            </p:column>
                            <p:column style="text-align: center">
                                <f:facet name="header">
                                    <h:outputText value="Action"/>
                                </f:facet>

                                <p:link 
                                    outcome="/admin/role/modifier"
                                    value="Modifier"
                                    title="Creation role utilisateur">
                                    <f:param name="pseudo" value="#{item.pseudo}"/>
                                </p:link>
                            </p:column>
                        </p:dataTable>
                    </h:form>
                </f:view>
            </ui:define>
        </ui:composition>

    </body>
</html>

projet NetBeans/applis-jee-mbds-ITUB/web/admin/role/modifier.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <f:metadata>  
        <f:viewParam name="pseudo" value="#{utilisateurRoleMBean.pseudo}"  
                     required="true"/>  
        <f:viewAction action="#{utilisateurRoleMBean.loadUtilisateurRole}"/>
        <f:viewAction action="#{internationalisation.loadLang()}"/>
    </f:metadata>

    <body>
        <ui:composition template="/WEB-INF/templates/primeface_top_left_foot.xhtml">

            <ui:define name="top">
                <p:menuitem value="Admin" outcome="/admin/utilisateur/index" />
                <p:menuitem value="Utilisateur Role" outcome="/admin/role/index" />
                <p:menuitem value="Modification"/>
            </ui:define>

            <ui:define name="content">
                <f:view>
                    <h:form>
                        <h1><h:outputText value="Créer utilisateur role"/></h1>
                        <p:panelGrid columns="2">
                            <p:outputLabel value="Pseudo:" for="pseudo" />
                            <p:inputText id="pseudo" value="#{utilisateurRoleMBean.utilisateurRole.pseudo}" title="Pseudo" required="true" requiredMessage="The Pseudo field is required."/>
                            <p:outputLabel value="Role:" for="role" />
                            <p:inputText id="role" value="#{utilisateurRoleMBean.utilisateurRole.role}" title="Role" />
                        </p:panelGrid>
                        <br/>

                        <p:commandButton 
                            id='modifier'
                            value="Modifier"
                            action="#{utilisateurRoleMBean.modifier()}"
                            >

                        </p:commandButton>
                    </h:form>
                </f:view>

            </ui:define>
        </ui:composition>

    </body>
</html>